### ISSUE TITLE
Seeing this warning on the site

### ISSUE THREAD

**Issue by AlanSwenson** [Studio-Center/sc-auditions#13]
`
moment.js:841 Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (https://studiocenterauditions.com/lib/moment/moment.js:850:105)
    at configFromString (https://studiocenterauditions.com/lib/moment/moment.js:970:32)
    at configFromInput (https://studiocenterauditions.com/lib/moment/moment.js:1473:13)
    at prepareConfig (https://studiocenterauditions.com/lib/moment/moment.js:1456:13)
    at createFromConfig (https://studiocenterauditions.com/lib/moment/moment.js:1423:44)
    at createLocalOrUTC (https://studiocenterauditions.com/lib/moment/moment.js:1505:16)
    at local__createLocal (https://studiocenterauditions.com/lib/moment/moment.js:1509:16)
    at utils_hooks__hooks (https://studiocenterauditions.com/lib/moment/moment.js:16:29)
    at Object.preprocessDate (https://studiocenterauditions.com/lib/angular-moment/angular-moment.min.js:1:2728)
    at e (https://studiocenterauditions.com/lib/angular-moment/angular-moment.min.js:1:4129)`

**Comment by doodersrage** [comment]
Just a deprecated warning on a failed Moment construct. Nothing to worry about, nothing broken.
